-- Queries
-- 1. Find the top 5 most liked posts.
-- 2. Get users who have posted at least 5 posts.
-- 3. Retrieve posts that have more than 100 likes.
-- 4. Find users who have never posted anything.
-- 5. Get users who have seen a specific reel but haven't liked it.
-- 6. Retrieve the total number of posts for each user.
-- 7. Find all reels that a user has watched but not liked.
-- 8. List all followers of a user who have liked at least one of their posts.
-- 9. Retrieve the most commented post in the last week.
-- 10. Find users who have sent more than 10 messages in the last day.
-- 11. Get all users who liked and commented on a specific post.
-- 12. Find the top 3 users with the most followers.
-- 13. List all users who have sent messages but never received any.
-- 14. Retrieve reels that have been watched by at least 10 unique users.
-- 15. Fetch the most liked story in the last 24 hours.
-- 16. Get users who have seen but never liked any stories.
-- 17. Find all reels that have received at least 5 comments and 10 likes.
-- 18. Retrieve the number of followers gained by each user in the last month.
-- 19. Find users who have posted at least one post and one story.
-- 20. Get all users who have received at least one direct message today.